dat <-read.table("dat/costvRT.dat")
par(mar=c(5,4,4,4))
plot(dat[,1],dat[,2]/1000000,ylim=c(0,30),typ="l",bty="n",main="PD reassigned time", xlab="% 2015 reassigned time",ylab="Cost [M$]")
mtext(side = 4, line = 3, 'Savings [M$]',col="red")
par(new=T)
plot(dat[,1],dat[,3]/1000000,ylim=c(0,10),typ="l",bty="n",xlab="",ylab="",yaxt="n",col="red")
axis(side = 4,col="red",col.axis="red")
dev.copy2pdf(file="plots/release-time.pdf")
readline(prompt="Press [enter] to continue")

dat <-read.table("dat/costvsab.dat")
par(mar=c(5,4,4,4))
plot(dat[,1],dat[,2]/1000000,ylim=c(0,30),typ="l",bty="n",main="Sabbaticals", xlab="% 2015 sabbaticals",ylab="Cost [M$]")
mtext(side = 4, line = 3, 'Savings [M$]',col="red")
par(new=T)
plot(dat[,1],dat[,3]/1000000,ylim=c(0,10),typ="l",bty="n",xlab="",ylab="",yaxt="n",col="red",yaxp  = c(0, 5, 1))
axis(side = 4,col="red",col.axis="red")
dev.copy2pdf(file="plots/sabbaticals.pdf")
readline(prompt="Press [enter] to continue")

dat <-read.table("dat/costvsize.dat")
par(mar=c(5,4,4,4))
plot(dat[,1],dat[,2]/1000000,ylim=c(0,30),typ="l",bty="n",main="Mean class size", xlab="mean class size",ylab="Cost [M$]")
mtext(side = 4, line = 3, 'Savings [M$]',col="red")
par(new=T)
plot(dat[,1],dat[,3]/1000000,ylim=c(0,10),typ="l",bty="n",xlab="",ylab="",yaxt="n",col="red",yaxp  = c(0, 5, 1))
axis(side = 4,col="red",col.axis="red")
dev.copy2pdf(file="plots/class-size.pdf")
readline(prompt="Press [enter] to continue")

dat <-read.table("dat/costvvis.dat")
par(mar=c(5,4,4,4))
plot(dat[,1],dat[,2]/1000000,ylim=c(0,30),typ="l",bty="n",main=expression(Visitors %->% adjuncts), xlab="% 2015 visitors",ylab="Cost [M$]")
mtext(side = 4, line = 3, 'Savings [M$]',col="red")
par(new=T)
plot(dat[,1],dat[,3]/1000000,ylim=c(0,10),typ="l",bty="n",xlab="",ylab="",yaxt="n",col="red",yaxp  = c(0, 5, 1))
axis(side = 4,col="red",col.axis="red")
dev.copy2pdf(file="plots/visitors-adjuncts.pdf")
readline(prompt="Press [enter] to continue")
