dat <-read.table("costvRT.dat")
options(scipen=5)
par(cex=1)
plot(dat[,1],dat[,2]/1000000,main="Research release time",xlab="% 2015 research release time",ylab="cost [M$]",type="l")
dev.copy2pdf(file="costvRT.pdf")
dev.copy(jpeg,'costvRT.jpg')
dev.off()
plot(dat[,1],dat[,3]/1000000,main="Research release time",xlab="% 2015 research release time",ylab="savings [M$]",type="l")
dev.copy2pdf(file="costvRTsav.pdf")
dev.copy(jpeg,'costvRTsav.jpg')
dev.off()

dat <-read.table("costvsab.dat")
options(scipen=5)
par(cex=1)
plot(dat[,1],dat[,2]/1000000,main="Sabbaticals",xlab="% 2015 sabbaticals",ylab="cost [M$]",type="l")
dev.copy2pdf(file="costvsab.pdf")
dev.copy(jpeg,'costvsab.jpg')
dev.off()
plot(dat[,1],dat[,3]/1000000,main="Sabbaticals",xlab="% 2015 sabbaticals",ylab="savings [M$]",type="l")
dev.copy2pdf(file="costvsabsav.pdf")
dev.copy(jpeg,'costvsabsav.jpg')
dev.off()

dat <-read.table("costvsize.dat")
options(scipen=5)
par(cex=1)
plot(dat[,1],dat[,2]/1000000,xlab="mean class size",ylab="cost [M$]",type="l")
dev.copy2pdf(file="costvsize.pdf")
dev.copy(jpeg,'costvsize.jpg')
dev.off()
plot(dat[,1],dat[,3]/1000000,xlab="mean class size",ylab="savings [M$]",type="l")
dev.copy2pdf(file="costvsizesav.pdf")
dev.copy(jpeg,'costvsizesav.jpg')
dev.off()

dat <-read.table("costvvis.dat")
options(scipen=5)
par(cex=1)
plot(dat[,1],dat[,2]/1000000,main="Visitors replaced with adjuncts",xlab="% 2015 visitors",ylab="cost [M$]",type="l")
dev.copy2pdf(file="costvvis.pdf")
dev.copy(jpeg,'costvvis.jpg')
dev.off()
plot(dat[,1],dat[,3]/1000000,main="Visitors replaced with adjuncts",xlab="% 2015 visitors",ylab="savings [M$]",type="l")
dev.copy2pdf(file="costvvissav.pdf")
dev.copy(jpeg,'costvvissav.jpg')
dev.off()
